### ISSUE TITLE
Prepare method raises exception in DBManager for tables with sql_variant type.

### ISSUE THREAD

**Issue by maxim-boligatov** [igor-tkachev/bltoolkit#331]
System.InvalidOperationException: SqlCommand.Prepare method requires all variable length parameters to have an explicitly set non-zero Size.
   at System.Data.SqlClient.SqlParameter.Prepare(SqlCommand cmd)
   at System.Data.SqlClient.SqlCommand.Prepare()
   at BLToolkit.Data.DbManager.InitParameters(CommandAction commandAction)
   at BLToolkit.Data.DbManager.Prepare()
   at BLToolkit.Data.DbManager.ExecuteForEach[T](IEnumerable`1 collection, MemberMapper[] members, Int32 maxBatchSize, ParameterProvider`1 getParameters)
   at BLToolkit.DataAccess.SqlQuery`1.ExecuteForEach(DbManager db, IEnumerable`1 collection, MemberMapper[] members, Int32 maxBatchSize, ParameterProvider`1 getParameters)
   at BLToolkit.DataAccess.SqlQuery`1.Update(DbManager db, Int32 maxBatchSize, IEnumerable`1 list)
   at BLToolkit.Data.Linq.Extensions.Update[T](DbManager dataContext, Int32 maxBatchSize, IEnumerable`1 list)
   at BLToolkit.Data.Linq.Extensions.Update[T](DbManager dataContext, IEnumerable`1 list)

[Workaround]
SetCommandParameters(CommandAction.Select, parameters);
AttachParameters(SelectCommand, parameters);
// Prepare(); // It works but most likely it should be reviewed by somebody who knows project and fixed.

**Comment by ras254** [comment]
I got same exception.

MS SQL database

CREATE TABLE [dbo].[tbl_value2](
	[id] [uniqueidentifier] NOT NULL,
	[integer_value] [int] NULL,
	[double_value] [float] NULL,
	[datetime_value] [datetime] NULL,
	[string_value] [nvarchar](max) NULL,
 CONSTRAINT [PK_tbl_value2] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

This is test data
https://www.dropbox.com/s/al7b0wbb61pm2fp/tbl_value2.zip?dl=0

And C# test code
    [TableName("tbl_value2")]
    public class Value
    {
        [PrimaryKey, MapField("id"), NotNull]
        public Guid Id { get; set; }

        [MapField("integer_value"), Nullable]
        public int? IntegerValue { get; set; }

        [MapField("double_value"), Nullable]
        public double? DoubleValue { get; set; }

        [MapField("datetime_value"), Nullable]
        public DateTime? DateTimeValue { get; set; }

        [MapField("string_value"), Nullable]
        public String StringValue { get; set; }
    }


            var connectionString = "Database connection string";
            using (var db = new DbManager(new Sql2008DataProvider(), connectionString))
            {
                var vals = db.GetTable<Value>().ToList();
                db.Update<Value>(vals); // Exception at this line
            }

**Comment by ras254** [comment]
fix #331 doesn't resolved my problem.
I debug code with my data and understood what DateTime2 parameter has Size = 0 and IsFixed = false, this throws exception.

This is solve my problem:
`case DbType.DateTime:`
`case DbType.DateTime2:`

after this line https://github.com/igor-tkachev/bltoolkit/blob/master/Source/Data/DbManager.cs#L2475

**Comment by ili** [comment]
You mean setting size for `DbType.DateTime & DbType.DateTime2`?

**Comment by ras254** [comment]
Yes
